### ISSUE TITLE
WP-Core-Feature Responsive Image

### ISSUE THREAD

**Issue by benthebear** [palasthotel/digitale-pracht#2]
Heyo @greatestview …

… does the theme support the Wordpress Core Feature for Responsive Images?

If it does, it doesnt seem to work correctly over here:
http://digitale-pracht.de/gute-kunden-schlechte-kunden/

All the best!
ben_

**Comment by greatestview** [comment]
Retina images with double width and height are currently preferred over standard dimensions, maybe that is what you mean with not working correctly?

On mobile, the image has currently an original dimension of 320x320 pixels and a CSS dimension of 277x277 pixels.
On desktop, the image has currently a original dimension of 786x786 pixels and a CSS dimension of 398x398 pixels.

Though there is still some inconsistency, I´ll have a look at that.

**Comment by benthebear** [comment]
Oh, I didn't make that clear … i'm talking about the Images that have been placed within the Text by Hand …

![bildschirmfoto 2016-05-09 um 14 27 01](https://cloud.githubusercontent.com/assets/49137/15113027/219da0b0-15f2-11e6-91cf-ff6ee1af8e5f.png)

It currently has the size of 2.024px × 1.139px but is scaled down with CSS to 846px × 476px

**Comment by greatestview** [comment]
Ah, I see. There is definitely some responsiveness going on, but I´ll do a check of the mechanism.

**Comment by greatestview** [comment]
Fixed with Version 1.12 https://github.com/palasthotel/digitale-pracht/commit/2d530affd66d890919d503b6a6eb583d71de8dd6.

We now have six image sizes (three for teasers, three for content images) and support for responsive images via WordPress core hooks. The img sizes attribute is calculated based on breakpoints and image width.

Retina support is removed now, since that is already part of WordPress core. If one needs advanced retina support, there are lots of plugins doing that already, e.g. [WP Retina 2x](https://de.wordpress.org/plugins/wp-retina-2x/).
