### ISSUE TITLE
Make Media Box within 1/1 Container 100% wide

### ISSUE THREAD

**Issue by benthebear** [palasthotel/digitale-pracht#5]
If you currently put a Media Box in a 1/1 Container and put an Image of 1295 Pixel width into it, theeen the Image is scaled down to 846 Pixel width. Maybe we want to make the 100% width again, @greatestview 

![bildschirmfoto 2017-01-10 um 16 27 33](https://cloud.githubusercontent.com/assets/49137/21812010/e92e0d4c-d751-11e6-81f6-a18cd8eab347.png)

**Comment by greatestview** [comment]
We should stay with the downscaled images by now. I looked into your issue and must say, that it would have several side effects, if we would stretch images to the layout borders:
- I’ve tried some images with a standard photo format as 4:3, 3:2 or 16:9, they become huge!
- Video-Boxes should work the same as image boxes. That means, they would become huge!
- That change would have an impact on all sites with a media box installed. The theme users should be confident, that their layout won’t break with an update.

Maybe in your case you could use a box prolog or a box title instead of the container titles?

A better way would be to introduce a non-default box style, e.g. »Stretched to maximum width«. That again has side-effects on all other boxes, which needs careful preparation. If you think that would be a nice feature please just create another issue.
